kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    username: gitlab-ci-token
    password:
      from_secret: TOKEN
    repo: registry.gitlab.com/yasser.isam/oidc
    registry: registry.gitlab.com
