kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    USERNAME:
      from_secret: docker_username

  commands:
    - echo $USERNAME


secrets:
  docker_username:
    external:
      name: secret/docker#username

  docker_password:
    external:
      name: secret/docker#password
