kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  environment:
    TOKEN:
      from_secret: TOKEN
  commands:
  - echo $TOKEN
  - docker login registry.gitlab.com -u gitlab-ci-token -p $TOKEN 
  - docker build -t registry.gitlab.com/yasser.isam/oidc .
  - docker push registry.gitlab.com/yasser.isam/oidc

