kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    USERNAME:
      from_secret: username
  commands:
    - echo $USERNAME

---
kind: s1ecret
name: username
get:
  path: secre1t/docker
  name: username

