kind: pipeline
name: default

steps:
- name: build
  image: debian
  settings:
    tags: latest
    value:
      from_secret: value
  commands:
    - cat ${value}
---
kind: secret
name: value
get:
  path: secret/message
  name: value
