kind: pipeline
name: default

steps:
- name: variable
  image: debian
  settings:
    tags: latest
    username:
      from_secret: username
  commands:
    - cat ${username}

kind: secret
name: username
get:
  path: secret
  name: message
