kind: pipeline
name: default

steps:
- name: build
  image: debian
  settings:
    tags: latest
  enviroment:
    PRUEBA: valor
    VALUE:
      from_secret: value
  commands:
    - export VALOR=1
    - echo $VALOR
    - echo $${VALUE}
    - echo $${VALOR}
---
kind: secret
name: value
get:
  path: secret/message
  name: value
