kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
    PRIVATE_KEY="$$ASDF"

  commands:
    - echo ${username}
    - echo $password
    - echo ${password}
    - echo $${password}
    - echo $PRIVATE_KEY
    - echo ${PRIVATE_KEY}

---
kind: secret
name: username
get:
  path: secret/docker
  name: username
 
---
kind: secret
name: password
get:
  path: secret/docker
  name: password
