kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    PRUEBA_1: valor
    value:
      from_secret: value
  commands:
    - export VALOR=1
    - echo $VALOR
    - echo $value
    - echo $PRUEBA_1
---
kind: secret
name: value
get:
  path: secret/message
  name: value
