kind: pipeline
name: default

steps:
- name: build
  image: debian
  settings:
    tags: latest
  enviroment:
    PRUEBA: "valor"
    VALUE:
      from_secret: value
  commands:
    - cat ${VALUE}
    - cat ${VALOR}
---
kind: secret
name: value
get:
  path: secret/message
  name: value
