kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    USERNAME:
      from_secret: username
  commands:
    - echo $USERNAME

---
kind: secret
name: username
get:
  path: secret/docker
  name: username

