kind: pipeline
name: default

steps:
- name: build
  image: debian
  enviroment:
    PRUEBA_1: valor
    PRUEBA:
      from_secret: value
  commands:
    - export VALOR=1
    - echo $VALOR
    - echo $PRUEBA
    - echo $PRUEBA_1
---
kind: secret
name: value
get:
  path: secret/message
  name: value
