kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0

  commands:
    - echo $GOOS
    - echo ${GOOS}
    - echo ${RPUEBA_1}
    - echo ${username}
    - echo ${password}

---
kind: secret
name: username
get:
  path: secret/docker
  name: username

---
kind: secret
name: password
get:
  path: secret/docker
  name: password
