kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    username:
      $secret: docker_username
  commands:
    - echo $username
    
---
kind: secret
type: external
data:
  docker_password: "secret/docker#password"
  docker_username: "secret/docker#username"
