kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password

  commands:
    - echo $USERNAME
    - echo ${USERNAME}
    - echo $PASSWORD
    - echo ${PASSWORD}


secrets:
  docker_username:
    external:
      name: secret/data/docker#username

  docker_password:
    external:
      name: secret/docker#password
