kind: pipeline
name: default

steps:
- name: build
  image: debian
  settings:
    PRUEBA_1: valor
    username:
      from_secret: username
    password:
      from_secret: password
  commands:
    - export VALOR=1
    - echo $VALOR
    - echo ${RPUEBA_1}
    - echo ${username}
    - echo ${password}

---
kind: secret
name: username
get:
  path: secret/docker
  name: username

---
kind: secret
name: password
get:
  path: secret/docker
  name: password
