kind: pipeline
name: default

steps:
- name: build
  image: debian
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
   commands
     - echo $USERNAME

---
kind: secret
name: username
get:
  path: secrets/docker
  name: username

---
kind: secret
name: password
get:
  path: secrets/docker
  name: password
